// Generates a comprehensive Canadian places dataset from the GeoNames CA dump.
// Input:  .geonames-cache/CA.txt  (https://download.geonames.org/export/dump/CA.zip)
//         src/skills/leads/canada.geo.json  (province polygons)
// Output: src/skills/leads/cities.data.json — array of [name, province, lat, lng, pop]
//
// We keep EVERY populated place (feature class P), including sub-1000 towns —
// small carriers are the whole point. Province is assigned by point-in-polygon
// on real coordinates (GeoNames' admin codes proved unreliable). Coords rounded
// to 4 decimals (~11 m).
import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const repo = path.resolve(__dirname, "..");
const SRC = path.join(repo, ".geonames-cache", "CA.txt");
const GEO = path.join(repo, ".geonames-cache", "canada.geojson");
const OUT = path.join(repo, "src", "skills", "leads", "cities.data.ts");

const CODE = {
  Quebec: "QC", "Newfoundland and Labrador": "NL", "British Columbia": "BC",
  Nunavut: "NU", "Northwest Territories": "NT", "New Brunswick": "NB",
  "Nova Scotia": "NS", Saskatchewan: "SK", Alberta: "AB",
  "Prince Edward Island": "PE", "Yukon Territory": "YT", Manitoba: "MB", Ontario: "ON",
};

const KEEP = new Set([
  "PPL", "PPLA", "PPLA2", "PPLA3", "PPLA4", "PPLA5",
  "PPLC", "PPLG", "PPLL", "PPLF", "PPLR", "PPLS", "PPLCH",
]);

// ---- province polygons with bbox + centroid for fast assignment ----
const geo = JSON.parse(fs.readFileSync(GEO, "utf8"));
const provs = geo.features.map((f) => {
  const code = CODE[f.properties.name];
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const poly of f.geometry.coordinates)
    for (const ring of poly)
      for (const [x, y] of ring) {
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
      }
  return { code, polys: f.geometry.coordinates, bbox: [minX, minY, maxX, maxY], cx: (minX + maxX) / 2, cy: (minY + maxY) / 2 };
});

function pointInRing(x, y, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1], xj = ring[j][0], yj = ring[j][1];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
function inFeature(x, y, p) {
  const [minX, minY, maxX, maxY] = p.bbox;
  if (x < minX || x > maxX || y < minY || y > maxY) return false;
  for (const poly of p.polys) {
    if (pointInRing(x, y, poly[0])) {
      let hole = false;
      for (let k = 1; k < poly.length; k++) if (pointInRing(x, y, poly[k])) { hole = true; break; }
      if (!hole) return true;
    }
  }
  return false;
}
function assignProvince(lng, lat) {
  for (const p of provs) if (inFeature(lng, lat, p)) return p.code;
  // Fallback: nearest province centroid (coastal/border points just outside polygons).
  let best = null, bd = Infinity;
  for (const p of provs) {
    const d = (p.cx - lng) ** 2 + (p.cy - lat) ** 2;
    if (d < bd) { bd = d; best = p.code; }
  }
  return best;
}

// ---- parse + assign ----
const lines = fs.readFileSync(SRC, "utf8").split("\n");
const byKey = new Map();
let fallbacks = 0;
for (const line of lines) {
  if (!line) continue;
  const c = line.split("\t");
  if (c[6] !== "P" || !KEEP.has(c[7])) continue;
  const name = c[1];
  if (!name) continue;
  const lat = Math.round(parseFloat(c[4]) * 1e4) / 1e4;
  const lng = Math.round(parseFloat(c[5]) * 1e4) / 1e4;
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;
  const pop = parseInt(c[14], 10) || 0;
  let inside = false;
  for (const p of provs) if (inFeature(lng, lat, p)) { inside = true; break; }
  if (!inside) fallbacks++;
  const prov = assignProvince(lng, lat);
  if (!prov) continue;
  const key = name.toLowerCase() + "|" + prov;
  const prev = byKey.get(key);
  if (!prev || pop > prev[4]) byKey.set(key, [name, prov, lat, lng, pop]);
}

const arr = [...byKey.values()].sort((a, b) => a[0].localeCompare(b[0], "en"));
// Emit as a .ts that JSON.parses a string literal: the compiler sees a single
// `string`, not a 19k-row tuple type, so typecheck stays fast.
const json = JSON.stringify(arr);
const ts =
  "// AUTO-GENERATED by scripts/gen-cities.mjs from the GeoNames CA dump. Do not edit.\n" +
  "// prettier-ignore\n" +
  `export default JSON.parse(${JSON.stringify(json)}) as [string, string, number, number, number][];\n`;
fs.writeFileSync(OUT, ts);

// Emit the province polygons the app renders, wrapped the same compiler-cheap way.
const GEO_OUT = path.join(repo, "src", "skills", "leads", "canada.geo.ts");
const geoTs =
  "// AUTO-GENERATED by scripts/gen-cities.mjs from the Canada provinces GeoJSON. Do not edit.\n" +
  'import type { FeatureCollection, MultiPolygon } from "geojson";\n' +
  "// prettier-ignore\n" +
  `export default JSON.parse(${JSON.stringify(JSON.stringify(geo))}) as FeatureCollection<MultiPolygon, { name: string }>;\n`;
fs.writeFileSync(GEO_OUT, geoTs);

const dist = {};
for (const e of arr) dist[e[1]] = (dist[e[1]] || 0) + 1;
console.log("kept entries:", arr.length);
console.log("by province:", JSON.stringify(dist));
console.log("nearest-centroid fallbacks:", fallbacks);
console.log("sub-1000 pop entries:", arr.filter((e) => e[4] < 1000).length);
console.log("output size:", (fs.statSync(OUT).size / 1024 / 1024).toFixed(2) + " MB");
