// Static reference data for the leads skill.
// All public information (Canadian geography, industry-standard equipment).
// No real carrier names or business data per Section 11.

// Trimmed to the four equipment types the brokerage actually books.
// Shippers re-exports this as FREIGHT_EQUIPMENT so the two automations align.
export const TRUCK_TYPES = [
  "Flatbed",
  "B-Train",
  "Dry Van",
  "Tanker",
] as const;
export type TruckType = (typeof TRUCK_TYPES)[number];

// Maximum fleet size (number of trucks). The UI slider, the Zod schema, the
// prompt, and the handler all clamp/enforce this range — a redundant hard cap
// the model is not allowed to exceed.
export const FLEET_CAP = { min: 5, max: 200, default: 50 } as const;

// Legacy fixed steps — still used by the shippers skill (SHIPPER_COUNTS).
export const LEAD_COUNTS = [5, 10, 15, 20, 30, 50] as const;
export type LeadCount = (typeof LEAD_COUNTS)[number];

// Leads now uses a continuous slider instead of fixed steps.
export const LEAD_RANGE = { min: 5, max: 100, default: 10 } as const;

export const PROVINCES = [
  { code: "AB", nameEn: "Alberta", nameFr: "Alberta" },
  { code: "BC", nameEn: "British Columbia", nameFr: "Colombie-Britannique" },
  { code: "MB", nameEn: "Manitoba", nameFr: "Manitoba" },
  { code: "NB", nameEn: "New Brunswick", nameFr: "Nouveau-Brunswick" },
  { code: "NL", nameEn: "Newfoundland & Labrador", nameFr: "Terre-Neuve-et-Labrador" },
  { code: "NS", nameEn: "Nova Scotia", nameFr: "Nouvelle-Écosse" },
  { code: "NT", nameEn: "Northwest Territories", nameFr: "Territoires du Nord-Ouest" },
  { code: "NU", nameEn: "Nunavut", nameFr: "Nunavut" },
  { code: "ON", nameEn: "Ontario", nameFr: "Ontario" },
  { code: "PE", nameEn: "Prince Edward Island", nameFr: "Île-du-Prince-Édouard" },
  { code: "QC", nameEn: "Quebec", nameFr: "Québec" },
  { code: "SK", nameEn: "Saskatchewan", nameFr: "Saskatchewan" },
  { code: "YT", nameEn: "Yukon", nameFr: "Yukon" },
] as const;
export type ProvinceCode = (typeof PROVINCES)[number]["code"];

export const TERRITORY_CODES = ["YT", "NT", "NU"] as const;

export const SECTORS = ["N", "S", "E", "W"] as const;
export type Sector = (typeof SECTORS)[number];

export const REGIONS = {
  maritimes: { codes: ["NB", "NS", "PE", "NL"], labelEn: "Maritimes", labelFr: "Maritimes" },
  prairies: { codes: ["AB", "SK", "MB"], labelEn: "Prairies", labelFr: "Prairies" },
  western: { codes: ["BC", "AB"], labelEn: "Western", labelFr: "Ouest" },
  central: { codes: ["ON", "QC"], labelEn: "Central", labelFr: "Centre" },
  territories: { codes: ["YT", "NT", "NU"], labelEn: "Territories", labelFr: "Territoires" },
  all: { codes: PROVINCES.map((p) => p.code), labelEn: "All Canada", labelFr: "Tout le Canada" },
} as const;
export type RegionKey = keyof typeof REGIONS;

// 13×12 = 156 lane permutations.
export function buildAllLanes(): string[] {
  const codes = PROVINCES.map((p) => p.code);
  const out: string[] = [];
  for (const a of codes) {
    for (const b of codes) {
      if (a !== b) out.push(`${a}→${b}`);
    }
  }
  return out;
}

// Comprehensive Canadian places — every populated place in the GeoNames CA
// dump (~19k cities/towns, weighted toward the small ones that matter for
// finding niche carriers). Generated by `scripts/gen-cities.mjs`; province is
// assigned by point-in-polygon on real coordinates. PLACES carries lat/lng for
// the map + paint-select; CITIES / CITY_TO_PROVINCE are name-keyed views for
// the type-ahead search.
export type { Place } from "./cities";
export { PLACES, CITIES, CITY_TO_PROVINCE } from "./cities";

export type City = string;
